name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag docker.pkg.github.com/hcgcloud/pterodactyl-wine-samp/pterodactyl-wine-samp:latest
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/hcgcloud/pterodactyl-wine-samp/pterodactyl-wine-samp:latest
